# Generated by Django 2.0.3 on 2020-05-06 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(blank=True, choices=[('PIZZA', 'Pizza'), ('SUB', 'Sub'), ('PASTASALAD', 'PastaSalad'), ('PLATTER', 'Platter')], max_length=64)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='active_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PastaSaladOrder',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastasalad_to_order_id', to='orders.Order')),
            ],
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dish_id_pizza', serialize=False, to='orders.Dish')),
                ('style', models.CharField(choices=[('REGULAR', 'Regular'), ('SICILIAN', 'Sicilian')], default='REGULAR', max_length=64)),
                ('topping_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('dish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platter_to_order_id', to='orders.Order')),
            ],
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dish_id_sub', serialize=False, to='orders.Dish')),
            ],
            bases=('orders.dish',),
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_id', to='orders.Order')),
            ],
            bases=('orders.pizza',),
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('sub_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Sub')),
                ('extra_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('extra_1', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_2', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_3', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_4', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_to_order_id', to='orders.Order')),
            ],
            bases=('orders.sub',),
        ),
    ]
