# Generated by Django 2.0.3 on 2020-02-26 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=64)),
                ('time', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='PastaSalad',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizestyle', models.CharField(choices=[('LREG', 'Large Regular'), ('SREG', 'Small Regular'), ('LSIC', 'Large Sicilian'), ('SSIC', 'Small Sicilian')], default='SREG', max_length=4)),
                ('topping_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubPrice',
            fields=[
                ('price_category', models.AutoField(primary_key=True, serialize=False)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_small', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PastaSaladOrder',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pastasalad_item_id', serialize=False, to='orders.Item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pastasalad_name', to='orders.PastaSalad')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pizzza_item_id', serialize=False, to='orders.Item')),
                ('sizestyle', models.CharField(choices=[('LREG', 'Large Regular'), ('SREG', 'Small Regular'), ('LSIC', 'Large Sicilian'), ('SSIC', 'Small Sicilian')], default='SREG', max_length=4)),
                ('topping_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('topping_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_1', to='orders.Toppings')),
                ('topping_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_2', to='orders.Toppings')),
                ('topping_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_3', to='orders.Toppings')),
                ('topping_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_4', to='orders.Toppings')),
                ('topping_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_5', to='orders.Toppings')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='platter_item_id', serialize=False, to='orders.Item')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlatterPrice',
            fields=[
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='platter_name', serialize=False, to='orders.Platter')),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sub_item_id', serialize=False, to='orders.Item')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1)),
                ('extra_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('extra_1', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_2', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_3', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
                ('extra_4', models.CharField(blank=True, choices=[('M', 'Mushrooms'), ('P', 'Peppers'), ('O', 'Onions'), ('C', 'Extra Cheese')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_price_category', to='orders.SubPrice'),
        ),
        migrations.AddField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_order_id', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_name', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='platterorder',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Platter'),
        ),
    ]
