# Generated by Django 2.0.3 on 2020-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200305_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platterprice',
            name='name',
        ),
        migrations.AddField(
            model_name='platter',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='platter',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.DeleteModel(
            name='PlatterPrice',
        ),
    ]
