# Generated by Django 2.0.3 on 2020-05-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200520_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='topping_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_1', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='topping_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='topping_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_3', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='topping_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_4', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='topping_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topping_5', to='orders.Topping'),
        ),
    ]
