# Generated by Django 2.0.3 on 2020-05-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200520_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaSaladOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pastasalad_dish_id', to='orders.Dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastasalad_to_order_id', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PlatterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platter_dish_id', to='orders.Dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platter_to_order_id', to='orders.Order')),
            ],
        ),
        migrations.RenameField(
            model_name='suborder',
            old_name='dish_id',
            new_name='dish',
        ),
    ]
