# Generated by Django 2.0.3 on 2020-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200520_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
    ]
