# Generated by Django 2.0.3 on 2020-05-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastasaladorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='platterorder',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='suborder',
            old_name='order_id',
            new_name='order',
        ),
    ]
