# Generated by Django 2.0.3 on 2020-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200520_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='extra_count',
        ),
        migrations.AlterField(
            model_name='suborder',
            name='extra_1',
            field=models.CharField(blank=True, choices=[('MUSHROOMS', 'Mushrooms'), ('PEPPERS', 'Peppers'), ('ONIONS', 'Onions'), ('EXTRA CHEESE', 'Extra Cheese')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='extra_2',
            field=models.CharField(blank=True, choices=[('MUSHROOMS', 'Mushrooms'), ('PEPPERS', 'Peppers'), ('ONIONS', 'Onions'), ('EXTRA CHEESE', 'Extra Cheese')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='extra_3',
            field=models.CharField(blank=True, choices=[('MUSHROOMS', 'Mushrooms'), ('PEPPERS', 'Peppers'), ('ONIONS', 'Onions'), ('EXTRA CHEESE', 'Extra Cheese')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='extra_4',
            field=models.CharField(blank=True, choices=[('MUSHROOMS', 'Mushrooms'), ('PEPPERS', 'Peppers'), ('ONIONS', 'Onions'), ('EXTRA CHEESE', 'Extra Cheese')], max_length=1, null=True),
        ),
    ]
