# Generated by Django 2.0.3 on 2020-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200527_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
